### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by talashuach** [epurdom/cobolt#2]
When trying to install Cobolt, it throws an error:
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ztaqj9s8/pytorch/setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
```

This can be fixed by changing the dependency from `pytorch` to `torch` in `setup.py`.

**Comment by boyinggong** [comment]
Thanks for trying out the package. I just have it fixed.
